cache: bundler
language: ruby
matrix:
  include:
    - rvm: ruby-head
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: ruby-head
    - rvm: jruby
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
install:
  - bundle install --retry=3
script: bundle exec rake
